# Write your MySQL query statement below
SELECT LEFT(trans_date,7) AS MONTH ,COUNTRY,COUNT(ID) AS TRANS_COUNT,
    SUM(STATE ="approved") AS  APPROVED_COUNT,SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
    SUM((STATE ="approved") * AMOUNT) AS APPROVED_TOTAL_AMOUNT 
FROM Transactions
GROUP BY MONTH ,COUNTRY 